#FROM is generated dynamically by the Makefile

ENV REGISTRY BUILD_REGISTRY
ENV TAG BUILD_TAG

ADD bin/rbd /bin/rbd
ADD bin/run.sh /bin/run.sh
RUN chmod +x /bin/rbd /bin/run.sh
RUN rm /app/conf.d/admin_keyring.toml && \
    rm /app/conf.d/mon_keyring.toml

ENTRYPOINT [ "/bin/run.sh" ]
