
stages:
- build
- deploy

build:
  stage: build
  script:
    - apk update
    - apk add make
    - make

deploy:
  stage: deploy
  script:
    - export BUILD_TAG=$CI_BUILD_TAG
    - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_TOKEN} -e ${REGISTRY_EMAIL} ${REGISTRY_URL}
    - apk update
    - apk add make
    - make
    - make release
  only:
    - tags
    - /^v([0-9]{1,3}[.]?){3}/
