#FROM is generated dynamically by the Makefile

ADD https://github.com/gambol99/rbd-fence/releases/download/0.0.1/rbd-manager_0.0.1_linux_x86_64.gz /bin/rbd-manager.gz
RUN gunzip /bin/rbd-manager.gz && \
    chmod +x /bin/rbd-manager

ENTRYPOINT ["/bin/rbd-manager"]

