#!/usr/bin/bash
#
#   Author: Rohith
#   Date: 2015-06-18 12:45:39 +0100 (Thu, 18 Jun 2015)
#
#  vim:ts=2:sw=2:et
#

RBD="/opt/bin/rbd"

annonce() {
  [ -n "$@" ] && echo "[v] $@"
}

usage() {
  cat <<EOF
  Usage: $(basename $0) -i|--image NAME -f FORMAT -s SIZE
  Creates a RBD block device and formats the volume into the correct filesystem

  -i|--image NAME     : the name of the image
  -f|--format FORMAT  : the file system format of the device (xfs, ext3 etc)
  -s|--size SIZE      : the size in megabytes of the block device
  -h|--usage          : display the usage menu
EOF
  [ -n "$@" ] && {
    echo "[error] $@";
    exit 1;
  }
  exit 0
}

list_devices() {
  local devices=`$RBD ls`
  [ $? -ne 0 ] && usage "failed to list the devices in ceph"
  [ -z "${devices}" ] && devices="none"
  echo ${devices}
}

# step: lets get the command line options
while [ $# -gt 0 ]; do
  case "$1" in
    -i|--image)    IMAGE=$2;   shift 2 ;;
    -f|--format)   FORMAT=$2;  shift 2 ;;
    -F|--features) FEATURES$2; shift 2 ;;
    -S|--shared)   SHARED=1;   shift 2 ;;
    -s|--size)     SIZE=$2;    shift 2 ;;
    -h|--help)     usage               ;;
    *)             shift               ;;
  esac
done

[ -z "${IMAGE}"  ] && usage "you have not specified a image name"
[ -z "${FORMAT}" ] && usage "you have not specified a file system format"
[ -z "${SIZE}"   ] && usage "you have not specified the size of the image"

# step: check of the device already exists
$(echo list_devices) | grep -q "${IMAGE}" && usage "the device: ${IMAGE} already exists, please remove it first"

annonce "Creating the block device: ${IMAGE}, size: ${SIZE}"

# step: create the device
${RBD} create ${IMAGE} -s ${SIZE} || usage "failed to create the block device in ceph, please investigate"

# step: mount the device
annonce "Mounting the block device: ${IMAGE} for formating"
DEVICE=`$RBD map ${IMAGE}`
[ $? -ne 0 ] && usage "failed to map the device: ${IMAGE}"

# step: format the block device
annonce "Formating the filesystem for image: ${IMAGE} to ${FORMAT}"
sudo /usr/sbin/wipefs -f ${DEVICE} || usage "failed to wipe the block device: ${DEVICE}"
sudo /usr/sbin/mkfs.${FORMAT} $DEVICE || usage "failed to format the block device: ${FORMAT}"
$RBD unmap ${DEVICE} || usage "failed to unmap the device: ${DEVICE}"

annonce "Successfully created the device"
